# Project: sdl02
# Makefile created by Dev-C++ 4.9.9.1

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = sdl_02.o $(RES)
LINKOBJ  = sdl_02.o $(RES)
LIBS =  -L"C:/Program Files/Dev-Cpp/lib" -L"C:/SDL/lib" -lmingw32 -lSDLmain -lSDL -mwindows  
INCS =  -I"C:/Program Files/Dev-Cpp/include"  -I"C:/SDL/include" 
CXXINCS =  -I"C:/Program Files/Dev-Cpp/include/c++"  -I"C:/Program Files/Dev-Cpp/include/c++/mingw32"  -I"C:/Program Files/Dev-Cpp/include/c++/backward"  -I"C:/Program Files/Dev-Cpp/include"  -I"C:/SDL/include" 
BIN  = sdl02.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before sdl02.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "sdl02.exe" $(LIBS)

sdl_02.o: sdl_02.cpp
	$(CPP) -c sdl_02.cpp -o sdl_02.o $(CXXFLAGS)
